[package]
name = "webrtc-apm-sys"
version = "0.1.0"
edition = "2024"
links = "webrtc-audio-processing"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = { version = "1.2.41", features = ["parallel"] }
